name: micr_ocr
description: Service to read MICR data from check images
version: 0.0.1
author: Todd Mannherz <todd.mannherz@gmail.com>

environment:
  sdk: '>=1.20.1 <2.0.0'

dependencies:
  args:
  crypto:
  http:
  mime:
  path:
  shelf:
  shelf_cors:
  shelf_exception_handler:
  shelf_response_formatter:
  shelf_route:
  sprintf:

dev_dependencies:
  test: